#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Extensions specified in the load list will be loaded by Robux
# We are using local fs for deep storage - not recommended for production - use S3, HDFS, or NFS instead
# We are using local derby for the metadata store - not recommended for production - use MySQL or Postgres instead

# If you specify `robux.extensions.loadList=[]`, Robux won't load any extension from file system.
# If you don't specify `robux.extensions.loadList`, Robux will load all the extensions under root extension directory.
# More info: https://robux.apache.org/docs/latest/operations/including-extensions.html
robux.extensions.loadList=["robux-hdfs-storage", "robux-kafka-indexing-service", "robux-datasketches", "robux-multi-stage-query", "robux-parquet-extensions"]

# If you have a different version of Hadoop, place your Hadoop client jar files in your hadoop-dependencies directory
# and uncomment the line below to point to your directory.
#robux.extensions.hadoopDependenciesDir=/my/dir/hadoop-dependencies


#
# Hostname
#
robux.host=localhost

#
# Logging
#

# Log all runtime properties on startup. Disable to avoid logging properties on startup:
robux.startup.logging.logProperties=true

#
# Zookeeper
#

robux.zk.service.host=localhost
robux.zk.paths.base=/robux

#
# Metadata storage
#

# For Derby server on your Robux Coordinator (only viable in a cluster with a single Coordinator, no fail-over):
robux.metadata.storage.type=derby
robux.metadata.storage.connector.connectURI=jdbc:derby://localhost:1527/var/robux/metadata.db;create=true
robux.metadata.storage.connector.host=localhost
robux.metadata.storage.connector.port=1527

# For MySQL (make sure to include the MySQL JDBC driver on the classpath):
#robux.metadata.storage.type=mysql
#robux.metadata.storage.connector.connectURI=jdbc:mysql://db.example.com:3306/robux
#robux.metadata.storage.connector.user=...
#robux.metadata.storage.connector.password=...

# For PostgreSQL:
#robux.metadata.storage.type=postgresql
#robux.metadata.storage.connector.connectURI=jdbc:postgresql://db.example.com:5432/robux
#robux.metadata.storage.connector.user=...
#robux.metadata.storage.connector.password=...

#
# Deep storage
#

# For local disk (only viable in a cluster if this is a network mount):
robux.storage.type=local
robux.storage.storageDirectory=var/robux/segments

# For HDFS:
#robux.storage.type=hdfs
#robux.storage.storageDirectory=/robux/segments

# For S3:
#robux.storage.type=s3
#robux.storage.bucket=your-bucket
#robux.storage.baseKey=robux/segments
#robux.s3.accessKey=...
#robux.s3.secretKey=...

#
# Indexing service logs
#

# For local disk (only viable in a cluster if this is a network mount):
robux.indexer.logs.type=file
robux.indexer.logs.directory=var/robux/indexing-logs

# For HDFS:
#robux.indexer.logs.type=hdfs
#robux.indexer.logs.directory=/robux/indexing-logs

# For S3:
#robux.indexer.logs.type=s3
#robux.indexer.logs.s3Bucket=your-bucket
#robux.indexer.logs.s3Prefix=robux/indexing-logs

#
# Service discovery
#

robux.selectors.indexing.serviceName=robux/overlord
robux.selectors.coordinator.serviceName=robux/coordinator

#
# Monitoring
#

robux.monitoring.monitors=["org.apache.robux.java.util.metrics.JvmMonitor", "org.apache.robux.server.metrics.ServiceStatusMonitor"]
robux.emitter=noop
robux.emitter.logging.logLevel=info

# Storage type of double columns
# ommiting this will lead to index double as float at the storage layer

robux.indexing.doubleStorage=double

#
# Security
#
robux.server.hiddenProperties=["robux.s3.accessKey","robux.s3.secretKey","robux.metadata.storage.connector.password", "password", "key", "token", "pwd"]


#
# SQL
#
robux.sql.enable=true

# Planning SQL query when there is aggregate distinct in the statement
robux.sql.planner.useGroupingSetForExactDistinct=true

#
# Lookups
#
robux.lookup.enableLookupSyncOnStartup=false
