#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

robux.service=robux/middleManager
robux.plaintextPort=8091

# Number of tasks per middleManager
robux.worker.capacity=16
robux.worker.baseTaskDirs=[\"var/robux/task\"]

# Task launch parameters
robux.indexer.runner.javaOptsArray=["-server","-Xms1g","-Xmx1g","-XX:MaxDirectMemorySize=1g","-Duser.timezone=UTC","-Dfile.encoding=UTF-8","-XX:+ExitOnOutOfMemoryError","-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"]

# HTTP server threads
robux.server.http.numThreads=60

# Processing threads and buffers on Peons
robux.indexer.fork.property.robux.processing.numMergeBuffers=2
robux.indexer.fork.property.robux.processing.buffer.sizeBytes=100MiB
robux.indexer.fork.property.robux.processing.numThreads=1

# Hadoop indexing
robux.indexer.task.hadoopWorkingPath=var/robux/hadoop-tmp
