[program:robux-service]
command=%(ENV_ROBUX_DEP_BIN_DIR)s/run-java %(ENV_COMMON_ROBUX_JAVA_OPTS)s %(ENV_SERVICE_ROBUX_JAVA_OPTS)s -cp %(ENV_ROBUX_COMMON_CONF_DIR)s:%(ENV_ROBUX_SERVICE_CONF_DIR)s:%(ENV_ROBUX_DEP_LIB_DIR)s org.apache.robux.cli.Main server %(ENV_ROBUX_SERVICE)s
redirect_stderr=true
priority=100
autorestart=false
stdout_logfile=%(ENV_ROBUX_LOG_PATH)s
