# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2.2"
services:
  robux-openldap:
    extends:
      file: docker-compose.base.yml
      service: robux-openldap
    env_file:
      - ./environment-configs/common-ldap

  robux-zookeeper-kafka:
    extends:
      file: docker-compose.base.yml
      service: robux-zookeeper-kafka
    env_file:
      - ./environment-configs/common-ldap
    depends_on:
      - robux-openldap

  robux-metadata-storage:
    extends:
      file: docker-compose.base.yml
      service: robux-metadata-storage
    env_file:
      - ./environment-configs/common-ldap
    environment:
      - ROBUX_INTEGRATION_TEST_GROUP=${ROBUX_INTEGRATION_TEST_GROUP}
    depends_on:
      - robux-openldap
      - robux-zookeeper-kafka

  robux-coordinator:
    extends:
      file: docker-compose.base.yml
      service: robux-coordinator
    env_file:
      - ./environment-configs/common-ldap
      - ./environment-configs/coordinator
    environment:
      - ROBUX_INTEGRATION_TEST_GROUP=${ROBUX_INTEGRATION_TEST_GROUP}
    depends_on:
      - robux-openldap
      - robux-metadata-storage
      - robux-zookeeper-kafka
      - robux-overlord

  robux-overlord:
    extends:
      file: docker-compose.base.yml
      service: robux-overlord
    env_file:
      - ./environment-configs/common-ldap
      - ./environment-configs/overlord
    environment:
      - ROBUX_INTEGRATION_TEST_GROUP=${ROBUX_INTEGRATION_TEST_GROUP}
    depends_on:
      - robux-openldap
      - robux-metadata-storage
      - robux-zookeeper-kafka

  robux-historical:
    extends:
      file: docker-compose.base.yml
      service: robux-historical
    env_file:
      - ./environment-configs/common-ldap
      - ./environment-configs/historical
    environment:
      - ROBUX_INTEGRATION_TEST_GROUP=${ROBUX_INTEGRATION_TEST_GROUP}
    depends_on:
      - robux-openldap
      - robux-zookeeper-kafka

  robux-middlemanager:
    extends:
      file: docker-compose.base.yml
      service: robux-middlemanager
    env_file:
      - ./environment-configs/common-ldap
      - ./environment-configs/middlemanager
    environment:
      - ROBUX_INTEGRATION_TEST_GROUP=${ROBUX_INTEGRATION_TEST_GROUP}
    depends_on:
      - robux-openldap
      - robux-zookeeper-kafka
      - robux-overlord

  robux-broker:
    extends:
      file: docker-compose.base.yml
      service: robux-broker
    env_file:
      - ./environment-configs/common-ldap
      - ./environment-configs/broker
    environment:
      - ROBUX_INTEGRATION_TEST_GROUP=${ROBUX_INTEGRATION_TEST_GROUP}
    depends_on:
      - robux-openldap
      - robux-coordinator
      - robux-zookeeper-kafka
      - robux-middlemanager
      - robux-historical

  robux-router:
    extends:
      file: docker-compose.base.yml
      service: robux-router
    env_file:
      - ./environment-configs/common-ldap
      - ./environment-configs/router
    environment:
      - ROBUX_INTEGRATION_TEST_GROUP=${ROBUX_INTEGRATION_TEST_GROUP}
    depends_on:
      - robux-openldap
      - robux-zookeeper-kafka
      - robux-coordinator
      - robux-broker
      - robux-overlord