# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: "robux.apache.org/v1alpha1"
kind: "Robux"
metadata:
  name: tiny-cluster
spec:
  image: robux/cluster:v1
  # Optionally specify image for all nodes. Can be specify on nodes also
  # imagePullSecrets:
  # - name: tutu
  startScript: /robux.sh
  podLabels:
    environment: stage
    release: alpha
  podAnnotations:
    dummy: k8s_extn_needs_atleast_one_annotation
  readinessProbe:
    httpGet:
      path: /status/health
      port: 8088
  securityContext:
    fsGroup: 0
    runAsUser: 0
    runAsGroup: 0
  containerSecurityContext:
    privileged: true
  services:
    - spec:
        type: ClusterIP
        clusterIP: None
  commonConfigMountPath: "/opt/robux/conf/robux/cluster/_common"
  jvm.options: |-
    -server
    -XX:MaxDirectMemorySize=10240g
    -Duser.timezone=UTC
    -Dfile.encoding=UTF-8
    -Dlog4j.debug
    -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
  log4j.config: |-
    <?xml version="1.0" encoding="UTF-8" ?>
    <Configuration status="WARN">
        <Appenders>
            <Console name="Console" target="SYSTEM_OUT">
                <PatternLayout pattern="%d{ISO8601} %p [%t] %c - %m%n"/>
            </Console>
        </Appenders>
        <Loggers>
            <Root level="info">
                <AppenderRef ref="Console"/>
            </Root>
        </Loggers>
    </Configuration>
  common.runtime.properties: |

    #
    # Zookeeper-less Robux Cluster
    #
    robux.zk.service.enabled=false
    robux.discovery.type=k8s
    robux.discovery.k8s.clusterIdentifier=robux-it
    robux.serverview.type=http
    robux.indexer.runner.type=httpRemote

    # Metadata Store
    robux.metadata.storage.type=derby
    robux.metadata.storage.connector.connectURI=jdbc:derby://localhost:1527/var/robux/metadata.db;create=true
    robux.metadata.storage.connector.host=localhost
    robux.metadata.storage.connector.port=1527
    robux.metadata.storage.connector.createTables=true

    # Deep Storage
    robux.storage.type=local
    robux.storage.storageDirectory=/robux/data/deepstorage

    #
    # Extensions
    #
    robux.extensions.loadList=["robux-avro-extensions","robux-hdfs-storage", "robux-kafka-indexing-service", "robux-datasketches", "robux-kubernetes-extensions"]

    #
    # Service discovery
    #
    robux.selectors.indexing.serviceName=robux/overlord
    robux.selectors.coordinator.serviceName=robux/coordinator

    robux.indexer.logs.type=file
    robux.indexer.logs.directory=/robux/data/task-logs
    robux.indexer.task.baseDir=/robux/data/task-base

    robux.lookup.enableLookupSyncOnStartup=false

  env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace

  nodes:
    brokers:
      # Optionally specify for running broker as Deployment
      # kind: Deployment
      nodeType: "broker"
      # Optionally specify for broker nodes
      # imagePullSecrets:
      # - name: tutu
      robux.port: 8088
      services:
        - spec:
            type: NodePort
            ports:
              - name: broker-service-port
                nodePort: 30100
                port: 8088
                protocol: TCP
                targetPort: 8088
          metadata:
            name: broker-%s-service
        - spec:
            type: ClusterIP
            clusterIP: None
      nodeConfigMountPath: "/opt/robux/conf/robux/cluster/query/broker"
      replicas: 1
      runtime.properties: |
        robux.service=robux/broker

        # HTTP server threads
        robux.broker.http.numConnections=5
        robux.server.http.numThreads=40

        # Processing threads and buffers
        robux.processing.buffer.sizeBytes=25000000
        robux.sql.enable=true
      extra.jvm.options: |-
        -Xmx512m
        -Xms512m
      volumeMounts:
        - mountPath: /robux/data
          name: data-volume
      volumes:
        - name: data-volume
          hostPath:
            path: REPLACE_VOLUMES/tmp
      resources:
        requests:
          memory: "800Mi"
        limits:
          memory: "800Mi"

    coordinators:
      # Optionally specify for running coordinator as Deployment
      # kind: Deployment
      nodeType: "coordinator"
      robux.port: 8088
      services:
        - spec:
            type: NodePort
            ports:
              - name: coordinator-service-port
                nodePort: 30200
                port: 8088
                protocol: TCP
                targetPort: 8088
          metadata:
            name: coordinator-%s-service
        - spec:
            type: ClusterIP
            clusterIP: None
      nodeConfigMountPath: "/opt/robux/conf/robux/cluster/master/coordinator-overlord"
      replicas: 1
      runtime.properties: |
        robux.service=robux/coordinator

        # HTTP server threads
        robux.coordinator.startDelay=PT30S
        robux.coordinator.period=PT30S

        # Configure this coordinator to also run as Overlord
        robux.coordinator.asOverlord.enabled=true
        robux.coordinator.asOverlord.overlordService=robux/overlord
        robux.indexer.queue.startDelay=PT30S
      extra.jvm.options: |-
        -Xmx800m
        -Xms800m
      volumeMounts:
        - mountPath: /robux/data
          name: data-volume
      volumes:
        - name: data-volume
          hostPath:
            path: REPLACE_VOLUMES/tmp
      resources:
        requests:
          memory: "1G"
        limits:
          memory: "1G"

    historicals:
      nodeType: "historical"
      robux.port: 8088
      services:
        - spec:
            type: NodePort
            ports:
              - name: historical-service-port
                nodePort: 30300
                port: 8088
                protocol: TCP
                targetPort: 8088
          metadata:
            name: historical-%s-service
        - spec:
            type: ClusterIP
            clusterIP: None
      nodeConfigMountPath: "/opt/robux/conf/robux/cluster/data/historical"
      replicas: 1
      runtime.properties: |
        robux.service=robux/historical
        robux.processing.buffer.sizeBytes=25000000
        robux.processing.numThreads=2
        # Segment storage
        robux.segmentCache.locations=[{"path":"/robux/data/segments","maxSize":10737418240}]
        robux.server.maxSize=10737418240
      extra.jvm.options: |-
        -Xmx512m
        -Xms512m
      volumeMounts:
        - mountPath: /robux/data
          name: data-volume
      volumes:
        - name: data-volume
          hostPath:
            path: REPLACE_VOLUMES/tmp
      resources:
        requests:
          memory: "1G"
        limits:
          memory: "1G"

    routers:
      nodeType: "router"
      robux.port: 8088
      services:
        - spec:
            type: NodePort
            ports:
              - name: router-service-port
                nodePort: 30400
                port: 8088
                protocol: TCP
                targetPort: 8088
          metadata:
            name: router-%s-service
        - spec:
            type: ClusterIP
            clusterIP: None
      nodeConfigMountPath: "/opt/robux/conf/robux/cluster/query/router"
      replicas: 1
      runtime.properties: |
        robux.service=robux/router
        robux.plaintextPort=8088

        # HTTP proxy
        robux.router.http.numConnections=50
        robux.router.http.readTimeout=PT5M
        robux.router.http.numMaxThreads=100
        robux.server.http.numThreads=100

        # Service discovery
        robux.router.defaultBrokerServiceName=robux/broker
        robux.router.coordinatorServiceName=robux/coordinator

        # Management proxy to coordinator / overlord: required for unified web console.
        robux.router.managementProxy.enabled=true

    middlemanagers:
      nodeType: "middleManager"
      nodeConfigMountPath: "/opt/robux/conf/robux/cluster/data/middleManager"
      robux.port: 8088
      services:
        - spec:
            type: NodePort
            ports:
              - name: middlemanager-service-port
                nodePort: 30500
                port: 8088
                protocol: TCP
                targetPort: 8088
          metadata:
            name: middlemanager-%s-service
        - spec:
            type: ClusterIP
            clusterIP: None
      replicas: 1
      runtime.properties: |
        robux.service=robux/middleManager
        robux.worker.capacity=2
        robux.indexer.runner.javaOpts=-server -Xms128m -Xmx128m -XX:MaxDirectMemorySize=256m -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/robux/data/tmp -XX:+ExitOnOutOfMemoryError -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
        robux.indexer.task.baseTaskDir=/robux/data/baseTaskDir
        robux.server.http.numThreads=10
        robux.indexer.fork.property.robux.processing.buffer.sizeBytes=25000000
        robux.indexer.fork.property.robux.processing.numMergeBuffers=2
        robux.indexer.fork.property.robux.processing.numThreads=1
      extra.jvm.options: |-
        -Xmx64m
        -Xms64m
      volumeMounts:
        - mountPath: /robux/data
          name: data-volume
      volumes:
        - name: data-volume
          hostPath:
            path: REPLACE_VOLUMES/tmp
      resources:
        requests:
          memory: "1G"
        limits:
          memory: "1G"
