:verify bin/verify-java
:verify bin/verify-default-ports
:notify bin/greet
:kill-timeout 10

!p10 zk bin/run-zk conf
coordinator-overlord bin/run-robux coordinator-overlord conf/robux/single-server/nano-quickstart
broker bin/run-robux broker conf/robux/single-server/nano-quickstart
router bin/run-robux router conf/robux/single-server/nano-quickstart
historical bin/run-robux historical conf/robux/single-server/nano-quickstart
!p90 middleManager bin/run-robux middleManager conf/robux/single-server/nano-quickstart
